#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

protected_branch='main'
protected_branch_dev='develop'
policy="\n\n[Policy] Never push code directly to the "$protected_branch" branch! (Prevented with pre-push hook.)\n\n"
policy_dev="\n\n[Policy] Never push code directly to the "$protected_branch" branch! (Prevented with pre-push hook.)\n\n"

current_branch=$(git branch --show-current)

do_exit(){
  echo -e $policy
  exit 1
}

do_exit_dev(){
  echo -e $policy_dev
  exit 1
}

if [ $current_branch = $protected_branch ]; then
  do_exit
fi

if [ $current_branch = $protected_branch_dev ]; then
  do_exit
fi

unset do_exit
unset do_exit_dev


exit 0
